#!/bin/bash

archDir=("installScripts")
configDir=( "archConfig"
            "bash"
            "bin"
            "compton"
            "git"
            "i3"
            "neovim"
            "terminal"
            "tmux"
)

sudo true
sudo rmmod pcspkr # Disable speaker beep
sudo cp -fv archConfig/dotfiles/pacman.conf /etc/

echo "==> Checking for system updates..."
sudo pacman -Syu --needed --noconfirm

echo "==> Updating Mirror list..."
sudo pacman-mirrors --method=rank

echo "==> Archlinux keyring"
sudo pacman -S --needed --noconfirm archlinux-keyring
sudo pacman -Syu --needed --noconfirm

echo "==> Installing Packages"
for i in "${archDir[@]}"
do
  echo "Entering in directory $i"
  cd $i
  sh ./install.sh
  cd ..
  echo "Leaving directory $i"
done

echo "==> System configuration"
for i in "${configDir[@]}"
do
  echo "Entering in directory $i"
  cd $i
  sh ./install.sh
  cd ..
  echo "Leaving directory $i"
done

echo "DONE"
