# Install docker
- name: Installing Docker
  shell: curl -fsSL https://get.docker.com | bash -

# Install docker-compose
- name: Installing docker-compose
  become: yes
  community.general.pacman:
    executable: yay
    state: present
    name:
        - docker-compose
    extra_args: --needed --noconfirm
