limit_default := ''
tags_default := ''
skip_default := ''
args_default := ''

# Check playbbok 
check limit=limit_default tags=tags_default skip=skip_default args=args_default:
  ansible-playbook main.yml {{args}} -i hosts --limit '{{limit}}' --tags '{{tags}}' --skip-tags '{{skip}}' --ask-pass --ask-become-pass --check

# Run playbook
run limit=limit_default tags=tags_default skip=skip_default args=args_default:
  ansible-playbook main.yml {{args}} -i hosts --limit '{{limit}}' --tags '{{tags}}' --skip-tags '{{skip}}' --ask-pass --ask-become-pass
