- hosts: all
  user: blackbird
  become: yes
  gather_facts: no
  tags: [ setup ]
  pre_tasks:
    - name: 'Updating archlinux-keyring'
      raw: 'sudo pacman -S --needed --noconfirm archlinux-keyring'
    - name: 'Updating Mirror list'
      raw: 'sudo pacman-mirrors --method=rank -c all'
    - name: 'Kill gpgconf to force restart'
      raw: 'gpgconf --kill all'
    - name: 'Updating system'
      raw: 'sudo pacman -Syyu --noconfirm'

- hosts: all
  user: blackbird
  roles:
  - { role: git, tags: ["gitconfig"] }

- hosts: all
  user: blackbird
  roles:
  - { role: aurhelpers, tags: ["aur"] }

- hosts: all
  user: blackbird
  roles:
  - { role: archconfig, tags: ["archconfig"] }

- hosts: all
  user: blackbird
  roles:
  - { role: install, tags: ["packages"] }

- hosts: all
  user: blackbird
  roles:
  - { role: neovim, tags: ["neovim"] }

- hosts: all
  user: blackbird
  roles:
  - { role: bash, tags: ["bashconfig"] }

- hosts: all
  user: blackbird
  roles:
  - { role: bin, tags: ["scripts"] }

- hosts: desktop
  user: blackbird
  roles:
  - { role: compton, tags: ["compton config", "extra"] }

- hosts: desktop
  user: blackbird
  roles:
  - { role: i3, tags: ["i3 config", "extra"] }

- hosts: desktop
  user: blackbird
  roles:
  - { role: termite, tags: ["termite config", "extra"] }

- hosts: desktop
  user: blackbird
  roles:
  - { role: tmux, tags: ["tmux config", "extra"] }

- hosts: desktop
  user: blackbird
  roles:
  - { role: X, tags: ["X config", "extra"] }